# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  win: circleci/windows@2.4.1
# Define a job to be invoked later in a workflow
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  AcceptanceTestWindows:
    executor: win/default
    steps:
      - run:
          name: Install Chrome
          command: |
            $Path = $env:TEMP; $Installer = "chrome_installer.exe"; Invoke-WebRequest "http://dl.google.com/chrome/install/375.126/chrome_installer.exe" -OutFile $Path\$Installer; Start-Process -FilePath $Path\$Installer -Args "/silent /install" -Verb RunAs -Wait; Remove-Item $Path\$Installer
      - run:
          name: Install node@16
          command: nvm install v16.13.2; nvm use v16.13.2
      - run:
          command: node --version
          name: Check updated node version
      - checkout
      - run:
          name: Install Packages
          command: npm install
      - run:
          name: Run Tests_engage (Windows + Integration)
          command: npm test -- --env=qa --password=comprovhl1 --userName=$userName
   
workflows:
  engage:
    jobs:
      - AcceptanceTestWindows