version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2
  aws-s3: circleci/aws-s3@3.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  VHLProdReaderUITest:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - run:
          name: Install Packages
          command: npm install
      - run:
          name: Run VHLProdReaderUITest
          command: npm test -- --env=qa --password=$password --userName=$userName
       
workflows:
  VHLProdReaderUITest:
    jobs:
      - VHLProdReaderUITest