# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2
  aws-s3: circleci/aws-s3@3.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  VHLReaderUI:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - run:
          name: Install Packages
          command: npm install
      - run:
          name: Run VHLReaderUI
          command: npm test -- --env=qa --password=comprovhl --userName=ramanjit.singh@comprotechnologies.com
      - run:
          name: Install Packages of Mailer
          command: npm install yargs fs nodemailer;
      - run:
          name: After Job - Send mail
          command: |
            ./utils; node mailer.js -projectName=qa:CIRCLE_PROJECT_REPONAME --mailingList=MAILINGLIST --emailId=emailId --emailPwd=emailPwd --jobResult=CIRCLE_BUILD_URL --triggerSource=triggerSource
   
workflows:
  VHLReaderUI:
    jobs:
      - VHLReaderUI